/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class presurecalculator extends javax.swing.JFrame {

	String[] pressureUnits = {
"unit",
"Pa",
"bar",
"atm",
"torr",
"psi",
"kgf/cm2"
};

	
double Pascal = 98066.5;
double Bar = 0.980665;
double Atmosphere = 0.967838;
double Tor = 735.5576;
double Pound_force_per_square_inch = 14.22357;
double Kilogram_force_per_square_centimeter = 1;


	/**
	 * Creates new form presurecalculator
	 */
	public presurecalculator() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                firstPressure = new javax.swing.JComboBox<>();
                t1 = new javax.swing.JTextField();
                From = new javax.swing.JLabel();
                To = new javax.swing.JLabel();
                t2 = new javax.swing.JTextField();
                firstPressureUnit = new javax.swing.JLabel();
                secondPressureUnit = new javax.swing.JLabel();
                secondPressure = new javax.swing.JComboBox<>();
                jButton18 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jLabel1.setBackground(new java.awt.Color(0, 0, 0));
                jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(102, 102, 102));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Pressure Calculator");

                firstPressure.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                firstPressure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "Pascal", "Bar", "Atmosphere", "Torr", "Pound-force per square inch", "Kilogram-force per square centimeter" }));
                firstPressure.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                firstPressureItemStateChanged(evt);
                        }
                });
                firstPressure.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                firstPressureActionPerformed(evt);
                        }
                });

                t1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

                From.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
                From.setText("From");

                To.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
                To.setText("To");

                t2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

                firstPressureUnit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
                firstPressureUnit.setText("Unit");

                secondPressureUnit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
                secondPressureUnit.setText("Unit");

                secondPressure.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                secondPressure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "Pascal", "Bar", "Atmosphere", "Torr", "Pound-force per square inch", "Kilogram-force per square centimeter" }));
                secondPressure.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                                secondPressureItemStateChanged(evt);
                        }
                });

                jButton18.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
                jButton18.setText("=");
                jButton18.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton18ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(From, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(firstPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(firstPressureUnit)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(secondPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(secondPressureUnit))
                                                        .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12))
                                        .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(From)
                                        .addComponent(To))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(secondPressureUnit)
                                                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(firstPressureUnit))
                                                .addGap(6, 6, 6))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(secondPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

                double amountToChange=Double.parseDouble(t1.getText());
                double amountChanged=0.0;
                double amountInAtm=0.0;

                switch(firstPressure.getSelectedItem().toString())
                {
                        case "Pascal": amountInAtm = amountToChange/Pascal;break;
                        case "Bar":amountInAtm = amountToChange/Bar;break;
                        case "Atmosphere":amountInAtm = amountToChange/Atmosphere;break;
                        case "Tor":amountInAtm = amountToChange/Tor;break;
                        case "Pound_force_per_square_inch":amountInAtm = amountToChange/Pound_force_per_square_inch;break;
                        case "Kilogram_force_per_square_centimeter":amountInAtm = amountToChange/Kilogram_force_per_square_centimeter;break;
                        default:amountInAtm = amountChanged/0.0;
                }

                switch(secondPressure.getSelectedItem().toString())
                {
                        case "Pascal":amountChanged = amountInAtm*Pascal;break;
                        case "Bar":amountChanged = amountInAtm*Bar;break;
                        case "Atmosphere":amountChanged = amountInAtm*Atmosphere;break;
                        case "Tor":amountChanged = amountInAtm*Tor;break;
                        case "Pound_force_per_square_inch":amountChanged = amountInAtm*Pound_force_per_square_inch;break;
                        case "Kilogram_force_per_square_centimeter":amountChanged = amountInAtm*Kilogram_force_per_square_centimeter;break;
                        default:amountChanged = amountInAtm*0.0;
                }

                String value = String.format("%.2f",amountChanged);

                t2.setText(value);
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton18ActionPerformed

        private void secondPressureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_secondPressureItemStateChanged
                int position=secondPressure.getSelectedIndex();
                secondPressureUnit.setText(pressureUnits[position]);
        }//GEN-LAST:event_secondPressureItemStateChanged

        private void firstPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPressureActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_firstPressureActionPerformed

        private void firstPressureItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_firstPressureItemStateChanged
                int position=firstPressure.getSelectedIndex();
                firstPressureUnit.setText(pressureUnits[position]);
        }//GEN-LAST:event_firstPressureItemStateChanged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(presurecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(presurecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(presurecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(presurecalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new presurecalculator().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel From;
        private javax.swing.JLabel To;
        private javax.swing.JComboBox<String> firstPressure;
        private javax.swing.JLabel firstPressureUnit;
        private javax.swing.JButton jButton18;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JComboBox<String> secondPressure;
        private javax.swing.JLabel secondPressureUnit;
        private javax.swing.JTextField t1;
        private javax.swing.JTextField t2;
        // End of variables declaration//GEN-END:variables
}
